const STATE_CITIES = {
  AK: ["Anchorage", "Fairbanks", "Sitka", "Ketchikan"],
  AL: ["Birmingham", "Huntsville", "Mobile", "Tuscaloosa"],
  AR: ["Fayetteville", "Fort Smith", "Jonesboro", "Hot Springs"],
  AZ: ["Tucson", "Mesa", "Scottsdale", "Flagstaff"],
  CA: ["Los Angeles", "San Francisco", "San Diego", "San Jose"],
  CO: ["Colorado Springs", "Aurora", "Boulder", "Fort Collins"],
  CT: ["Bridgeport", "New Haven", "Stamford", "Waterbury"],
  DE: ["Wilmington", "Newark", "Middletown", "Smyrna"],
  FL: ["Miami", "Orlando", "Tampa", "Jacksonville"],
  GA: ["Savannah", "Augusta", "Columbus", "Macon"],
  HI: ["Hilo", "Kailua", "Pearl City", "Lahaina"],
  IA: ["Cedar Rapids", "Davenport", "Sioux City", "Iowa City"],
  ID: ["Nampa", "Idaho Falls", "Meridian", "Pocatello"],
  IL: ["Chicago", "Aurora", "Peoria", "Rockford"],
  IN: ["Fort Wayne", "Evansville", "South Bend", "Bloomington"],
  KS: ["Wichita", "Overland Park", "Kansas City", "Lawrence"],
  KY: ["Louisville", "Lexington", "Bowling Green", "Covington"],
  LA: ["New Orleans", "Shreveport", "Lafayette", "Lake Charles"],
  MA: ["Worcester", "Springfield", "Cambridge", "Lowell"],
  MD: ["Baltimore", "Frederick", "Rockville", "Bethesda"],
  ME: ["Portland", "Lewiston", "Bangor", "South Portland"],
  MI: ["Detroit", "Grand Rapids", "Ann Arbor", "Flint"],
  MN: ["Minneapolis", "Rochester", "Duluth", "Bloomington"],
  MO: ["Kansas City", "St. Louis", "Springfield", "Columbia"],
  MS: ["Gulfport", "Hattiesburg", "Biloxi", "Tupelo"],
  MT: ["Billings", "Missoula", "Great Falls", "Bozeman"],
  NC: ["Charlotte", "Durham", "Greensboro", "Wilmington"],
  ND: ["Fargo", "Grand Forks", "Minot", "West Fargo"],
  NE: ["Omaha", "Bellevue", "Grand Island", "Kearney"],
  NH: ["Manchester", "Nashua", "Dover", "Rochester"],
  NJ: ["Newark", "Jersey City", "Paterson", "Elizabeth"],
  NM: ["Albuquerque", "Las Cruces", "Rio Rancho", "Roswell"],
  NV: ["Las Vegas", "Reno", "Henderson", "Sparks"],
  NY: ["New York City", "Buffalo", "Rochester", "Syracuse"],
  OH: ["Cleveland", "Cincinnati", "Toledo", "Akron"],
  OK: ["Tulsa", "Norman", "Broken Arrow", "Lawton"],
  OR: ["Portland", "Eugene", "Bend", "Medford"],
  PA: ["Philadelphia", "Pittsburgh", "Allentown", "Erie"],
  RI: ["Warwick", "Cranston", "Pawtucket", "Newport"],
  SC: ["Charleston", "Greenville", "Myrtle Beach", "Rock Hill"],
  SD: ["Sioux Falls", "Rapid City", "Aberdeen", "Brookings"],
  TN: ["Memphis", "Knoxville", "Chattanooga", "Clarksville"],
  TX: ["Houston", "Dallas", "San Antonio", "El Paso"],
  UT: ["Provo", "West Valley City", "Ogden", "St. George"],
  VA: ["Virginia Beach", "Norfolk", "Arlington", "Alexandria"],
  VT: ["Burlington", "Rutland", "South Burlington", "Barre"],
  WA: ["Seattle", "Tacoma", "Spokane", "Vancouver"],
  WI: ["Milwaukee", "Green Bay", "Kenosha", "Racine"],
  WV: ["Huntington", "Morgantown", "Parkersburg", "Wheeling"],
  WY: ["Casper", "Laramie", "Gillette", "Rock Springs"]
};
