// State abbreviations mapped to full names and capitals
const STATE_DATA = {
  AL: { name: "Alabama", capital: "Montgomery" },
  AK: { name: "Alaska", capital: "Juneau" },
  AZ: { name: "Arizona", capital: "Phoenix" },
  AR: { name: "Arkansas", capital: "Little Rock" },
  CA: { name: "California", capital: "Sacramento" },
  CO: { name: "Colorado", capital: "Denver" },
  CT: { name: "Connecticut", capital: "Hartford" },
  DE: { name: "Delaware", capital: "Dover" },
  FL: { name: "Florida", capital: "Tallahassee" },
  GA: { name: "Georgia", capital: "Atlanta" },
  HI: { name: "Hawaii", capital: "Honolulu" },
  ID: { name: "Idaho", capital: "Boise" },
  IL: { name: "Illinois", capital: "Springfield" },
  IN: { name: "Indiana", capital: "Indianapolis" },
  IA: { name: "Iowa", capital: "Des Moines" },
  KS: { name: "Kansas", capital: "Topeka" },
  KY: { name: "Kentucky", capital: "Frankfort" },
  LA: { name: "Louisiana", capital: "Baton Rouge" },
  ME: { name: "Maine", capital: "Augusta" },
  MD: { name: "Maryland", capital: "Annapolis" },
  MA: { name: "Massachusetts", capital: "Boston" },
  MI: { name: "Michigan", capital: "Lansing" },
  MN: { name: "Minnesota", capital: "Saint Paul" },
  MS: { name: "Mississippi", capital: "Jackson" },
  MO: { name: "Missouri", capital: "Jefferson City" },
  MT: { name: "Montana", capital: "Helena" },
  NE: { name: "Nebraska", capital: "Lincoln" },
  NV: { name: "Nevada", capital: "Carson City" },
  NH: { name: "New Hampshire", capital: "Concord" },
  NJ: { name: "New Jersey", capital: "Trenton" },
  NM: { name: "New Mexico", capital: "Santa Fe" },
  NY: { name: "New York", capital: "Albany" },
  NC: { name: "North Carolina", capital: "Raleigh" },
  ND: { name: "North Dakota", capital: "Bismarck" },
  OH: { name: "Ohio", capital: "Columbus" },
  OK: { name: "Oklahoma", capital: "Oklahoma City" },
  OR: { name: "Oregon", capital: "Salem" },
  PA: { name: "Pennsylvania", capital: "Harrisburg" },
  RI: { name: "Rhode Island", capital: "Providence" },
  SC: { name: "South Carolina", capital: "Columbia" },
  SD: { name: "South Dakota", capital: "Pierre" },
  TN: { name: "Tennessee", capital: "Nashville" },
  TX: { name: "Texas", capital: "Austin" },
  UT: { name: "Utah", capital: "Salt Lake City" },
  VT: { name: "Vermont", capital: "Montpelier" },
  VA: { name: "Virginia", capital: "Richmond" },
  WA: { name: "Washington", capital: "Olympia" },
  WV: { name: "West Virginia", capital: "Charleston" },
  WI: { name: "Wisconsin", capital: "Madison" },
  WY: { name: "Wyoming", capital: "Cheyenne" }
};

// Label positions for state abbreviations (x, y in SVG coordinates)
const STATE_LABELS = {
  AL: { x: 675, y: 430 },
  AK: { x: 165, y: 530 },
  AZ: { x: 215, y: 430 },
  AR: { x: 570, y: 400 },
  CA: { x: 105, y: 350 },
  CO: { x: 305, y: 330 },
  CT: { x: 893, y: 225 },
  DE: { x: 855, y: 295 },
  FL: { x: 755, y: 505 },
  GA: { x: 725, y: 420 },
  HI: { x: 310, y: 545 },
  ID: { x: 195, y: 210 },
  IL: { x: 610, y: 310 },
  IN: { x: 650, y: 300 },
  IA: { x: 540, y: 250 },
  KS: { x: 450, y: 340 },
  KY: { x: 700, y: 330 },
  LA: { x: 580, y: 470 },
  ME: { x: 905, y: 130 },
  MD: { x: 835, y: 295 },
  MA: { x: 900, y: 205 },
  MI: { x: 665, y: 220 },
  MN: { x: 510, y: 165 },
  MS: { x: 625, y: 435 },
  MO: { x: 555, y: 340 },
  MT: { x: 280, y: 140 },
  NE: { x: 430, y: 275 },
  NV: { x: 155, y: 310 },
  NH: { x: 893, y: 170 },
  NJ: { x: 870, y: 270 },
  NM: { x: 290, y: 420 },
  NY: { x: 835, y: 195 },
  NC: { x: 780, y: 365 },
  ND: { x: 430, y: 150 },
  OH: { x: 710, y: 275 },
  OK: { x: 460, y: 390 },
  OR: { x: 130, y: 175 },
  PA: { x: 800, y: 245 },
  RI: { x: 907, y: 218 },
  SC: { x: 765, y: 390 },
  SD: { x: 430, y: 205 },
  TN: { x: 680, y: 370 },
  TX: { x: 430, y: 460 },
  UT: { x: 225, y: 320 },
  VT: { x: 875, y: 155 },
  VA: { x: 790, y: 320 },
  WA: { x: 145, y: 110 },
  WV: { x: 755, y: 305 },
  WI: { x: 575, y: 185 },
  WY: { x: 300, y: 230 }
};
