// State abbreviations mapped to full names and capitals
const STATE_DATA = {
  AK: { name: "Alaska", capital: "Juneau" },
  AL: { name: "Alabama", capital: "Montgomery" },
  AR: { name: "Arkansas", capital: "Little Rock" },
  AZ: { name: "Arizona", capital: "Phoenix" },
  CA: { name: "California", capital: "Sacramento" },
  CO: { name: "Colorado", capital: "Denver" },
  CT: { name: "Connecticut", capital: "Hartford" },
  DE: { name: "Delaware", capital: "Dover" },
  FL: { name: "Florida", capital: "Tallahassee" },
  GA: { name: "Georgia", capital: "Atlanta" },
  HI: { name: "Hawaii", capital: "Honolulu" },
  IA: { name: "Iowa", capital: "Des Moines" },
  ID: { name: "Idaho", capital: "Boise" },
  IL: { name: "Illinois", capital: "Springfield" },
  IN: { name: "Indiana", capital: "Indianapolis" },
  KS: { name: "Kansas", capital: "Topeka" },
  KY: { name: "Kentucky", capital: "Frankfort" },
  LA: { name: "Louisiana", capital: "Baton Rouge" },
  MA: { name: "Massachusetts", capital: "Boston" },
  MD: { name: "Maryland", capital: "Annapolis" },
  ME: { name: "Maine", capital: "Augusta" },
  MI: { name: "Michigan", capital: "Lansing" },
  MN: { name: "Minnesota", capital: "Saint Paul" },
  MO: { name: "Missouri", capital: "Jefferson City" },
  MS: { name: "Mississippi", capital: "Jackson" },
  MT: { name: "Montana", capital: "Helena" },
  NC: { name: "North Carolina", capital: "Raleigh" },
  ND: { name: "North Dakota", capital: "Bismarck" },
  NE: { name: "Nebraska", capital: "Lincoln" },
  NH: { name: "New Hampshire", capital: "Concord" },
  NJ: { name: "New Jersey", capital: "Trenton" },
  NM: { name: "New Mexico", capital: "Santa Fe" },
  NV: { name: "Nevada", capital: "Carson City" },
  NY: { name: "New York", capital: "Albany" },
  OH: { name: "Ohio", capital: "Columbus" },
  OK: { name: "Oklahoma", capital: "Oklahoma City" },
  OR: { name: "Oregon", capital: "Salem" },
  PA: { name: "Pennsylvania", capital: "Harrisburg" },
  RI: { name: "Rhode Island", capital: "Providence" },
  SC: { name: "South Carolina", capital: "Columbia" },
  SD: { name: "South Dakota", capital: "Pierre" },
  TN: { name: "Tennessee", capital: "Nashville" },
  TX: { name: "Texas", capital: "Austin" },
  UT: { name: "Utah", capital: "Salt Lake City" },
  VA: { name: "Virginia", capital: "Richmond" },
  VT: { name: "Vermont", capital: "Montpelier" },
  WA: { name: "Washington", capital: "Olympia" },
  WI: { name: "Wisconsin", capital: "Madison" },
  WV: { name: "West Virginia", capital: "Charleston" },
  WY: { name: "Wyoming", capital: "Cheyenne" }
};

// Label positions for state abbreviations (x, y in SVG coordinates)
const STATE_LABELS = {
  AK: { x: 106, y: 536 },
  AL: { x: 664, y: 449 },
  AR: { x: 581, y: 389 },
  AZ: { x: 167, y: 364 },
  CA: { x: 65, y: 291 },
  CO: { x: 319, y: 284 },
  CT: { x: 872, y: 193 },
  DE: { x: 839, y: 249 },
  FL: { x: 755, y: 490 },
  GA: { x: 739, y: 424 },
  HI: { x: 311, y: 577 },
  IA: { x: 531, y: 228 },
  ID: { x: 201, y: 123 },
  IL: { x: 602, y: 283 },
  IN: { x: 649, y: 292 },
  KS: { x: 479, y: 292 },
  KY: { x: 670, y: 311 },
  LA: { x: 575, y: 460 },
  MA: { x: 899, y: 170 },
  MD: { x: 820, y: 263 },
  ME: { x: 911, y: 102 },
  MI: { x: 676, y: 185 },
  MN: { x: 532, y: 112 },
  MO: { x: 566, y: 305 },
  MS: { x: 591, y: 433 },
  MT: { x: 235, y: 114 },
  NC: { x: 806, y: 340 },
  ND: { x: 448, y: 102 },
  NE: { x: 469, y: 233 },
  NH: { x: 877, y: 134 },
  NJ: { x: 846, y: 230 },
  NM: { x: 304, y: 390 },
  NV: { x: 150, y: 280 },
  NY: { x: 829, y: 175 },
  OH: { x: 721, y: 259 },
  OK: { x: 462, y: 395 },
  OR: { x: 97, y: 111 },
  PA: { x: 819, y: 214 },
  RI: { x: 892, y: 183 },
  SC: { x: 764, y: 397 },
  SD: { x: 454, y: 187 },
  TN: { x: 658, y: 354 },
  TX: { x: 442, y: 493 },
  UT: { x: 228, y: 262 },
  VA: { x: 794, y: 294 },
  VT: { x: 861, y: 135 },
  WA: { x: 92, y: 51 },
  WI: { x: 590, y: 156 },
  WV: { x: 757, y: 276 },
  WY: { x: 300, y: 183 }
};
