// State abbreviations mapped to full names and capitals
const STATE_DATA = {
  AK: { name: "Alaska", capital: "Juneau" },
  AL: { name: "Alabama", capital: "Montgomery" },
  AR: { name: "Arkansas", capital: "Little Rock" },
  AZ: { name: "Arizona", capital: "Phoenix" },
  CA: { name: "California", capital: "Sacramento" },
  CO: { name: "Colorado", capital: "Denver" },
  CT: { name: "Connecticut", capital: "Hartford" },
  DE: { name: "Delaware", capital: "Dover" },
  FL: { name: "Florida", capital: "Tallahassee" },
  GA: { name: "Georgia", capital: "Atlanta" },
  HI: { name: "Hawaii", capital: "Honolulu" },
  IA: { name: "Iowa", capital: "Des Moines" },
  ID: { name: "Idaho", capital: "Boise" },
  IL: { name: "Illinois", capital: "Springfield" },
  IN: { name: "Indiana", capital: "Indianapolis" },
  KS: { name: "Kansas", capital: "Topeka" },
  KY: { name: "Kentucky", capital: "Frankfort" },
  LA: { name: "Louisiana", capital: "Baton Rouge" },
  MA: { name: "Massachusetts", capital: "Boston" },
  MD: { name: "Maryland", capital: "Annapolis" },
  ME: { name: "Maine", capital: "Augusta" },
  MI: { name: "Michigan", capital: "Lansing" },
  MN: { name: "Minnesota", capital: "Saint Paul" },
  MO: { name: "Missouri", capital: "Jefferson City" },
  MS: { name: "Mississippi", capital: "Jackson" },
  MT: { name: "Montana", capital: "Helena" },
  NC: { name: "North Carolina", capital: "Raleigh" },
  ND: { name: "North Dakota", capital: "Bismarck" },
  NE: { name: "Nebraska", capital: "Lincoln" },
  NH: { name: "New Hampshire", capital: "Concord" },
  NJ: { name: "New Jersey", capital: "Trenton" },
  NM: { name: "New Mexico", capital: "Santa Fe" },
  NV: { name: "Nevada", capital: "Carson City" },
  NY: { name: "New York", capital: "Albany" },
  OH: { name: "Ohio", capital: "Columbus" },
  OK: { name: "Oklahoma", capital: "Oklahoma City" },
  OR: { name: "Oregon", capital: "Salem" },
  PA: { name: "Pennsylvania", capital: "Harrisburg" },
  RI: { name: "Rhode Island", capital: "Providence" },
  SC: { name: "South Carolina", capital: "Columbia" },
  SD: { name: "South Dakota", capital: "Pierre" },
  TN: { name: "Tennessee", capital: "Nashville" },
  TX: { name: "Texas", capital: "Austin" },
  UT: { name: "Utah", capital: "Salt Lake City" },
  VA: { name: "Virginia", capital: "Richmond" },
  VT: { name: "Vermont", capital: "Montpelier" },
  WA: { name: "Washington", capital: "Olympia" },
  WI: { name: "Wisconsin", capital: "Madison" },
  WV: { name: "West Virginia", capital: "Charleston" },
  WY: { name: "Wyoming", capital: "Cheyenne" }
};

// Label positions computed from polygon centroids, with manual overrides
const STATE_LABELS = {
  AK: { x: 100, y: 512 },
  AL: { x: 661, y: 425 },
  AR: { x: 555, y: 385 },
  AZ: { x: 205, y: 376 },
  CA: { x: 81, y: 283 },
  CO: { x: 326, y: 285 },
  CT: { x: 872, y: 187 },
  DE: { x: 840, y: 256 },
  FL: { x: 756, y: 507 },
  GA: { x: 725, y: 421 },
  HI: { x: 312, y: 578 },
  IA: { x: 532, y: 224 },
  ID: { x: 196, y: 144 },
  IL: { x: 606, y: 266 },
  IN: { x: 655, y: 265 },
  KS: { x: 449, y: 304 },
  KY: { x: 678, y: 316 },
  LA: { x: 567, y: 470 },
  MA: { x: 883, y: 169 },
  MD: { x: 819, y: 259 },
  ME: { x: 905, y: 92 },
  MI: { x: 674, y: 182 },
  MN: { x: 517, y: 130 },
  MO: { x: 552, y: 307 },
  MS: { x: 609, y: 430 },
  MT: { x: 283, y: 98 },
  NC: { x: 789, y: 345 },
  ND: { x: 422, y: 102 },
  NE: { x: 427, y: 235 },
  NH: { x: 879, y: 138 },
  NJ: { x: 848, y: 226 },
  NM: { x: 306, y: 387 },
  NV: { x: 140, y: 248 },
  NY: { x: 821, y: 169 },
  OH: { x: 713, y: 249 },
  OK: { x: 463, y: 370 },
  OR: { x: 101, y: 132 },
  PA: { x: 793, y: 222 },
  RI: { x: 890, y: 181 },
  SC: { x: 767, y: 386 },
  SD: { x: 423, y: 169 },
  TN: { x: 663, y: 355 },
  TX: { x: 427, y: 462 },
  UT: { x: 223, y: 264 },
  VA: { x: 789, y: 300 },
  VT: { x: 860, y: 134 },
  WA: { x: 122, y: 58 },
  WI: { x: 586, y: 164 },
  WV: { x: 755, y: 280 },
  WY: { x: 303, y: 192 }
};
